<?php

namespace App\Model;

/**
 * One line of a player's score breakdown: the stat count, its label and
 * the points it produced. The sum of a player's lines is their total;
 * the lines themselves are the box-score explanation text (legacy
 * scoreString), generated by the same computation as the total.
 */
class ScoreLine
{
    public function __construct(
        public readonly string $label,
        public readonly int $points,
        public readonly int|float|null $count = null,
    ) {
    }
}
